services:
  app:
    image: todo-front
    build:
      context: ./todo-frontend 
      dockerfile: Dockerfile
    ports:
      - 3000:80
    container_name: todo-front
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - AUTH=yes
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=p@ssw0rd
      - MONGO_INITDB_DATABASE=the_database
    volumes: 
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongodata:/data/db
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./todo-backend/redis_data:/data
  server:
    image: todo-back
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    volumes:
      - ./todo-backend/:/usr/src/app/
    ports:
      - 3001:3001
    environment: 
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://admin:p%40ssw0rd@mongo:27017/the_database?authSource=admin
      - PORT=3001
    container_name: todo-back
  debug-helper:
    image: busybox

volumes:
  mongodata: